<a href="https://colab.research.google.com/github/bosdata/roadmap/blob/main/otigo10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
## Let us generate an array with 10 random values
rand_arr = np.random.randn(10)
print(rand_arr)

[-0.56375673 -1.02465223  0.29594936  0.84466388  0.48112383 -0.65610097
  1.86844717 -0.1260594  -0.83851304  0.92242333]


In [ ]:
## Accesing the 6th entry

## To get an element we access by the index
print(rand_arr[5])

-0.656100970636411


In [ ]:
## Accessing 4th entry
print(rand_arr[3])

0.8446638784238447


In [ ]:
#### Accessing myultiple array access 6th to 8th element

print(rand_arr[5:8])

## Print the first 5
print(rand_arr[:5])

[-0.65610097  1.86844717 -0.1260594 ]
[-0.56375673 -1.02465223  0.29594936  0.84466388  0.48112383]


In [ ]:
print(rand_arr[2::3])

[ 0.29594936 -0.65610097 -0.83851304]


In [ ]:
### access the 3rd 6th and 9th
print("Index of values to access: ", np.arange(2,10,3))
print(rand_arr[np.arange(2,10,3)])

Index of values to access:  [2 5 8]
[ 0.29594936 -0.65610097 -0.83851304]


**Accessing arrays using logical operators**

In [ ]:
## Suppose we needed values less than zero and entries greater than zero
print('Values greator than zero: ', rand_arr[rand_arr>0])
print('Values greator than zero: ', rand_arr[rand_arr<0])


Values greator than zero:  [0.29594936 0.84466388 0.48112383 1.86844717 0.92242333]
Values greator than zero:  [-0.56375673 -1.02465223 -0.65610097 -0.1260594  -0.83851304]
[0.29594936 0.84466388 0.48112383 1.86844717 0.92242333]
[-0.56375673 -1.02465223 -0.65610097 -0.1260594  -0.83851304]


In [ ]:
# Accessing elements that don't follow particular pattern for an array(say extract values lie 1st, 3rd 5th)
print(np.arange(0,5,2))
print(rand_arr[np.arange(0,6,2)])
print(rand_arr)

[0 2 4]
[-0.56375673  0.29594936  0.48112383]
[-0.56375673 -1.02465223  0.29594936  0.84466388  0.48112383 -0.65610097
  1.86844717 -0.1260594  -0.83851304  0.92242333]
