<a href="https://colab.research.google.com/github/bosdata/roadmap/blob/main/ottigo_grp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
##########       Quiz one
# Createa 3x3 Numpy array
import numpy as np
zero_array = np.zeros((3,3))
print(zero_array)

# Create a 1 D Numpy array with values ranging from 0 to 9
arr1 = np.array([i for i in range(0,10)])
print(arr1)

## Reshape 1D array of 12 elements into 3x4 2D array
oneD= np.linspace(70,100,12);
twoD =oneD.reshape((3,4));
print(oneD);
print(twoD)
# print(len(oneD))

##Create a 2D arra and then transpose it
arr2 = np.arange(1,7).reshape(2,3)
arr2_trans = arr2.T
print(arr2_trans)

## Find the sum and mean and sd of an array
arr_data = np.array([j for j in range(0,210, 10)])
arr_data_sum = sum(arr_data)
arr_data_sd = np.std(arr_data)
arr_data_mean= np.mean(arr_data)
print(f"The sum: {arr_data_sum} standard deviation: {arr_data_sd} and mean: {arr_data_mean} for the array: {arr_data}")

## Dot porduct of 2D
mat1 = np.arange(1,7).reshape(2,3)
mat2 = np.eye(3,2)
mat1_dot_mat2 = mat1 @ mat2
print(mat1_dot_mat2)


## Generate a 5 by 5 array of random integers ...
random_array = np.random.randint(10, 51, size=(5, 5))
print(random_array)



############### Indexing and slicing
#extract a specific row
arr3 = np.arange(10,40,5).reshape(2,3)
print(arr3[0,1]) #Extracts the second element in the first row
print(arr3[:, -1]) #extract the last column in arr3


#Slicing 2-D arrays
arr4 = np.arange(0, 24).reshape(4,6)
print(arr4[0:2, 3:])   #extract every elemnt from column 3 to the very end on row 1 and 2

# Use boolean indexing to select elements from an array based on a condition (e.g., all elements greater than 5 import numpy as np
arr = np.array([2, 5, 7, 1, 9, 4, 6])
result = arr[arr > 5]
print("Original array:", arr)
print("Elements greater than 5:", result)


############ Conditional logic
#Replace all values greater than 25 with 100 in a given array. import numpy as np
arr = np.array([10, 26, 30, 5, 40, 18])
arr[arr > 25] = 100
print("Updated array:", arr)

#From a NumPy array of integers, extract all even numbers.
scores = np.array([45, 80, 72, 90, 60, 88])
labels = []
for Scores in scores:
  if Scores > 75:
    labels.append("High")
  else:
    labels.append("Low")
print(labels)


############################### Loop
# iterate over a 2D array
arrD= np.arange(0,24).reshape(2,12)
for index,ArrD in enumerate(arrD):
  print((index,ArrD))


#count how many values in a random array are divisible by 3. import numpy as np
arr = np.random.randint(1, 100, size=15)
Count1 = np.sum(arr % 3 == 0)
print("Array:", arr)
print("Number of values divisible by 3:", Count1)


#Write a function that takes a NumPy array and returns the mean, median, and standard deviation. import numpy as np def array_statistics(arr):
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)
# return mean_val, median_val, std_val
# data = np.array([10, 20, 30, 40, 50]) mean, median, std = array_statistics(data)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[ 70.          72.72727273  75.45454545  78.18181818  80.90909091
  83.63636364  86.36363636  89.09090909  91.81818182  94.54545455
  97.27272727 100.        ]
[[ 70.          72.72727273  75.45454545  78.18181818]
 [ 80.90909091  83.63636364  86.36363636  89.09090909]
 [ 91.81818182  94.54545455  97.27272727 100.        ]]
[[1 4]
 [2 5]
 [3 6]]
The sum: 2100 standard deviation: 60.55300708194983 and mean: 100.0 for the array: [  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200]
[[1. 2.]
 [4. 5.]]
[[24 33 47 31 14]
 [29 22 35 17 43]
 [47 34 14 27 11]
 [12 48 41 46 35]
 [18 22 23 35 35]]
15
[20 35]
[[ 3  4  5]
 [ 9 10 11]]
Original array: [2 5 7 1 9 4 6]
Elements greater than 5: [7 9 6]
Updated array: [ 10 100 100   5 100  18]
['Low', 'High', 'Low', 'High', 'Low', 'High']
(0, array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))
(1, array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]))
Arr